import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import CustomNavbar from "@/components/CustomNavbar";
import { Suspense } from "react";
import { Spinner } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CustomNavbar />
          <Suspense fallback={<Spinner />}>
            <div className="mt-16">{children}</div>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
